---
# Simple script execution without checksum verification
- hosts: windows_servers
  roles:
    - role: ansible-powershell-github-executor
      vars:
        powershell_script_url: "https://raw.githubusercontent.com/myorg/scripts/main/simple-script.ps1"
        powershell_script_args: "-Verbose"
